import { Search } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import EmptyState from '../components/EmptyState.jsx';
import { tournamentApi, unwrapData } from '../features/tournaments/api.js';
import { TournamentLogo, dateText } from '../features/tournaments/TournamentUi.jsx';
import { TOURNAMENT_SCOPE, formatTournamentLabel } from '../features/tournaments/constants.js';

export default function PublicTournamentsPage() {
  const [filters, setFilters] = useState({ search: '', scope: '', past: '' });
  const [tournaments, setTournaments] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); try { const params = Object.fromEntries(Object.entries(filters).filter(([, value]) => value)); const response = await tournamentApi.listPublic(params); setTournaments(unwrapData(response).tournaments || []); setError(''); } catch (requestError) { setError(requestError.userMessage); } finally { setLoading(false); } }, [filters]);
  useEffect(() => { load(); }, [load]);
  return <><header><p className="eyebrow">Tournament directory</p><h1 className="page-title">Tournaments</h1><p className="page-copy">Browse upcoming, ongoing, and past FootStream tournaments with fixtures, results, standings, awards, and statistics.</p></header><form onSubmit={(e) => { e.preventDefault(); load(); }} className="mt-7 grid gap-3 rounded-2xl border border-white/[0.07] bg-white/[0.025] p-4 md:grid-cols-[1fr_180px_160px_auto]"><input className="field-input" placeholder="Search tournament" value={filters.search} onChange={(e) => setFilters({ ...filters, search: e.target.value })} /><select className="field-input" value={filters.scope} onChange={(e) => setFilters({ ...filters, scope: e.target.value })}><option value="">All scopes</option><option value={TOURNAMENT_SCOPE.INTER_COLLEGE}>Inter College</option><option value={TOURNAMENT_SCOPE.INTRA_COLLEGE}>Intra College</option></select><select className="field-input" value={filters.past} onChange={(e) => setFilters({ ...filters, past: e.target.value })}><option value="">Upcoming/Ongoing</option><option value="true">Past</option></select><button className="primary-button"><Search size={16} /> Filter</button></form><section className="mt-7">{loading ? <div className="skeleton h-80" /> : error ? <div className="rounded-2xl border border-red-300/20 bg-red-300/10 p-5 text-red-100">{error}</div> : tournaments.length === 0 ? <EmptyState title="No public tournaments" message="Approved and published tournaments will appear here." /> : <div className="grid gap-5 lg:grid-cols-2 xl:grid-cols-3">{tournaments.map((tournament) => <Link key={tournament.id} to={`/tournaments/${tournament.slug}`} className="rounded-3xl border border-white/[0.08] bg-white/[0.035] p-5 transition hover:border-lime-300/30"><div className="flex gap-4"><TournamentLogo tournament={tournament} /><div><p className="text-xs font-black uppercase tracking-[0.2em] text-lime-300/70">{formatTournamentLabel(tournament.scope)}</p><h2 className="font-display text-2xl font-black">{tournament.name}</h2><p className="text-sm text-white/45">{tournament.seasonLabel} · {dateText(tournament.startDate)}</p></div></div><p className="mt-4 text-sm text-white/55">{tournament.primaryVenue} · {tournament.city}</p><p className="mt-2 text-sm text-white/45">{formatTournamentLabel(tournament.competitionFormat)} · {tournament.participants?.length || 0} participants</p></Link>)}</div>}</section></>;
}
